### ISSUE TITLE
Does not work with head of beets master

### ISSUE THREAD

**Issue by jonschmidt** [snejus/beets-bandcamp#3]
I had to use head of beets master to get around a Python 3.8 error, and I am getting this when using the plugin

```
/Users/jmschmidt/Projects/beets-bandcamp % beet import ~/Desktop/filez/Danny\ Wolfers\ -\ The\ Land\ Is\ Entranced\ With\ Peace
Traceback (most recent call last):
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/bin/beet", line 11, in <module>
    load_entry_point('beets==1.5.0', 'console_scripts', 'beet')()
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/__init__.py", line 1278, in main
    _raw_main(args)
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/__init__.py", line 1265, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/commands.py", line 960, in import_func
    import_files(lib, paths, query)
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/commands.py", line 930, in import_files
    session.run()
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/importer.py", line 341, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/Users/jmschmidt/.local/lib/python3.7/site-packages/six-1.15.0-py3.7.egg/six.py", line 703, in reraise
    raise value
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/importer.py", line 1365, in lookup_candidates
    task.lookup_candidates()
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/importer.py", line 653, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/autotag/match.py", line 467, in tag_album
    extra_tags):
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/plugins.py", line 582, in decorated
    for v in generator(*args, **kwargs):
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/autotag/hooks.py", line 632, in album_candidates
    extra_tags):
  File "/Users/jmschmidt/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/plugins.py", line 392, in candidates
    extra_tags):
TypeError: candidates() takes 5 positional arguments but 6 were given
```

**Comment by snejus** [comment]
Was this using `master` or `dev` branch?

**Comment by jonschmidt** [comment]
Both I think, but I can try again with a specific one if you want

**Comment by snejus** [comment]
Just checked it - they've introduced some breaking changes so it broke. Try to add something now - I provisionally patched it for now but cannot guarantee it will work completely (for obvious reasons). Though do let me know if things break - I'm happy to have a look at them since I'll be building some stuff on top of the new metadata that's now available.

**Comment by snejus** [comment]
This should be fully working now in `0.7.0`. :)
